# Utilizar la imagen oficial de Node.js versión 14 como imagen base
FROM node:14

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /var/app

# Copiar los archivos del proyecto al directorio de trabajo dentro del contenedor
COPY . .

# Instalar las dependencias del proyecto
RUN npm install

# Exponer el puerto 8080 para que la aplicación sea accesible desde fuera del contenedor
EXPOSE 8080

# Comando para arrancar la aplicación
CMD ["npm", "start"]
